name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

env:
  PACKAGE_NAME: provider-proxmox
  IMAGE_NAME: ghcr.io/${{ github.repository }}/provider-proxmox

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build provider
        run: |
          make build

      - name: Package provider
        run: |
          mkdir -p package
          cp bin/provider package/
          cp -R package/crds package/
          cat <<EOF > package/crossplane.yaml
          apiVersion: meta.pkg.crossplane.io/v1
          kind: Provider
          metadata:
            name: ${{ env.PACKAGE_NAME }}
          spec:
            controller:
              image: ${IMAGE_NAME}:${GITHUB_SHA}
          EOF

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push OCI image
        uses: docker/build-push-action@v4
        with:
          context: package
          file: - <<EOF
            FROM scratch
            COPY . /
            CMD ["/provider"]
            EOF
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest,${{ env.IMAGE_NAME }}:${{ github.sha }}
          labels: |
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}

      - name: Logout from GitHub Container Registry
        if: always()
        run: docker logout ghcr.io
