name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: {}
env:
  PACKAGE_NAME: provider-proxmox
  PACKAGE_ROOT: github.com/joekky/provider-proxmox
  IMAGE_NAME: ghcr.io/${{ github.repository }}
  CONTROLLER_IMAGE: ghcr.io/${{ github.repository }}-controller
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - name: Build provider binary and generate CRDs
        run: |
          make build
          echo "Generating CRDs..."
          make manifests
          echo "CRD generation completed. Contents of package/crds/:"
          ls -la package/crds/
          if [ -f package/crds/proxmox.crossplane.io_containers.yaml ]; then
            echo "Content of proxmox.crossplane.io_containers.yaml:"
            cat package/crds/proxmox.crossplane.io_containers.yaml
          else
            echo "proxmox.crossplane.io_containers.yaml not found!"
          fi
        # run: make build
      - name: Check CRD content
        run: |
          echo "Content of proxmox.crossplane.io_containers.yaml:"
          cat /home/runner/work/provider-proxmox/provider-proxmox/package/crds/proxmox.crossplane.io_containers.yaml
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push controller image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t ${{ env.CONTROLLER_IMAGE }}:${{ github.sha }} \
            --push \
            -f cluster/images/provider-proxmox/Dockerfile \
            .
      - name: Install Crossplane CLI
        run: |
          curl -sL https://raw.githubusercontent.com/crossplane/crossplane/master/install.sh | sh
          sudo mv crossplane /usr/local/bin/
      - name: Update crossplane.yaml with controller image
        run: |
          sed -i "s|image:.*|image: ${{ env.CONTROLLER_IMAGE }}:${{ github.sha }}|g" package/crossplane.yaml
      - name: Build provider package
        run: |
          crossplane xpkg build -o provider-proxmox.xpkg --ignore ".github/**/*.yml" --verbose
      - name: Push provider package
        run: |
          crossplane xpkg push ${{ env.IMAGE_NAME }}:${{ github.sha }} -f provider-proxmox.xpkg
      - name: Logout from GitHub Container Registry
        if: always()
        run: docker logout ghcr.io
