name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: {}

env:
  PACKAGE_NAME: provider-proxmox
  PACKAGE_ROOT: github.com/joekky/provider-proxmox
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/provider-proxmox

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Build provider binary
        run: make build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Crossplane CLI
        run: |
          curl -sL https://raw.githubusercontent.com/crossplane/crossplane/master/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Build and push provider image
        run: |
          make -C cluster/images/provider-proxmox img.build
          make -C cluster/images/provider-proxmox img.push

      - name: Build OCI package
        run: make -C cluster/images/provider-proxmox package

      - name: Push OCI package to GHCR
        run: |
          crossplane package push provider-proxmox.tar.gz --tag ghcr.io/joekky/provider-proxmox:latest

      - name: Logout from GitHub Container Registry
        if: always()
        run: docker logout ghcr.io
