name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: {}

env:
  PACKAGE_NAME: provider-proxmox
  PACKAGE_ROOT: github.com/joekky/provider-proxmox
  IMAGE_NAME: ghcr.io/${{ github.repository }}/provider-proxmox

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Build provider binary
        run: make build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push provider image
        env:
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
        run: |
          make -C cluster/images/provider-proxmox img.build
          make -C cluster/images/provider-proxmox img.push

      - name: Logout from GitHub Container Registry
        if: always()
        run: docker logout ghcr.io
